ui: mocha-bdd
tunnel:
  type: ngrok
  authtoken: LsVZFxFqgxA4h7ibWV9V_iuA9afbQwaSnGqH9dApL
scripts:
  - "/node_modules/expect.js/expect.js"
  - "/node_modules/sinon/pkg/sinon-1.16.1.js"
  - "/test/support/config.js"
  - "/build/auth0.js"
browsers:
  - name: chrome
    version: -2..latest
  - name: safari
    version: -2..latest
  - name: firefox
    version: -2..latest
  - name: ie
    version: 8..latest
