#!/usr/bin/env node

var exec = require('child_process').exec;

var serve = exec('serve test -p 9009', function () {
  process.exit(0);
});

serve.stdout.pipe(process.stdout);
serve.stderr.pipe(process.stderr);

var run_tests = exec('mocha-phantomjs --timeout 7000 http://localhost:9009', function () {
  serve.kill();
});

run_tests.stdout.pipe(process.stdout);
run_tests.stderr.pipe(process.stderr);